### ISSUE TITLE
Parser ends a square early - no turns case

### ISSUE THREAD

**Issue by ghost** [xaviertorgerson/micromouse#122]
If the path is completely straight, the parser still ends a square early.

For example, try to solve for the box directly in front of the robot. Or the one in front of that.

Not an issue when solving for the middle of a competition maze, because it's impossible to drive straight to the middle. :-)

**Comment by awglyde** [comment]
This should be solved by Pull Request #123 by @BishopofWales. This issue can likely be closed since the pull request was approved and merged.

**Comment by ghost** [comment]
Yup you're right, I forgot to reference this issue in the merge.
