### ISSUE TITLE
Add acceleration parameters to motion functions

### ISSUE THREAD

**Issue by QuentinTorg** [xaviertorgerson/micromouse#14]
All motion functions should have maximum accel and decel values passed to them instead of using defined or global variables.  We will need this when we start adjusting acceleration on during our runs.  This change will also affect the input parameters of the motionCalc class.

**Comment by QuentinTorg** [comment]
These are now individual functions that alter single values at a time

**Comment by amiller27** [comment]
Fixed by [this commit](https://github.com/Pitt-RAS/micromouse/commit/8144f256c6c8abe0c5f02c6dc54e7a8bb71e3324)
