### ISSUE TITLE
Move initialization into a function

### ISSUE THREAD

**Issue by ghost** [xaviertorgerson/micromouse#20]
In response to us forgetting to set the analog write resolution in the testing branch, we decided it makes sense to be able to do all initialization with one function call so that it's clear what needs to be initialized to make the rest of our code work properly.

Things that should be in there include at least setting the analog frequency, setting the analog resolution, and zeroing the encoders.

**Comment by QuentinTorg** [comment]
Should this be part of the conf file?

**Comment by amiller27** [comment]
I don't think there should be any code in conf.  We could just mark it with strongly worded comments in the sketch to separate it from the stuff that's temporary

**Comment by ghost** [comment]
Yeah, actually micromouse.ino is gettting pretty small already in the master branch. We probably don't need to worry about this issue for testing stuff.
