### ISSUE TITLE
Stuck in first cell

### ISSUE THREAD

**Issue by ghost** [xaviertorgerson/micromouse#57]
Sometimes the robot drives to the center of the first cell and stops, then nods. Sometimes it drives to the cell edge, stops abruptly (not good), then nods. Sometimes it nods correctly, sometimes it doesn't.
Occurs randomly for all we can tell, which is unsettling.

Some possible suspects are: beginFromBack() in the continuous driver, the starting orientation mechanism, low level EEPROM operations, load/save operations in the base driver class, the continuous driver in general, path bugs (which could be reproduced in software), improper use of range sensors, a menu bug, memory mismanagement, memory leaks, using all our memory, a logging bug, bad builds/uploads (unlikely), hardware issues (unlikely), puberty, or sabotage.

**Comment by amiller27** [comment]
The stopping abruptly was in beginFromBack, and that's fixed
