### ISSUE TITLE
Write functions for sensors_nav.cpp

### ISSUE THREAD

**Issue by QuentinTorg** [xaviertorgerson/micromouse#6]
The functions in sensors_nav.cpp should measure the distance between the specified sensor and the next wall, and determine if the wall is part of the current cell or the next cell

The threshold value for what wall distance is part of the current cell or the next cell should be stored in conf.h.

**Comment by QuentinTorg** [comment]
Is there a better method for determining if a wall is present than a set cutoff distance?

**Comment by QuentinTorg** [comment]
Add functions that use the angled sensors to see if there is a wall present in the oncoming right and left cells

**Comment by xaviertorgerson** [comment]
Different project structure
