### ISSUE TITLE
I2Cdev library is patched under the same name as upstream

### ISSUE THREAD

**Issue by ghost** [xaviertorgerson/micromouse#78]
Users who have upstream I2Cdev installed can't build the project.

Make a fork "I2CdevMod" and modify our code to use that instead of upstream. (Just like EncoderMod)

**Comment by ghost** [comment]
Also need to confirm that this is the build issue we were having, and that Arduino 1.8.0 and Teensyduino 1.34 are _not_ the problem.

**Comment by asaba96** [comment]
I can confirm that it builds just fine with Arduino 1.6.12 and teensy 1.34, as well as with Arduino 1.8.0, both times with the modified library. I believe this problem was due to the library, not the newer versions.

**Comment by ghost** [comment]
Confirmed working with Arduino 1.8.0 and Teensyduino 1.34 on Linux.

**Comment by ghost** [comment]
Whoops. In turn, the MPU9150 lib uses I2Cdev. So I'm going to have to patch that to refer to I2CdevMod.

Unless somebody has a better idea.

**Comment by amiller27** [comment]
Ideally we would fix the actual problem in I2Cdevlib which prevents it from dealing with multiple i2c buses so that our solution would be backwards compatible with I2Cdevlib, but that would be hard.

**Comment by ghost** [comment]
Agreed.

**Comment by ghost** [comment]
@amiller27: I used your idea for renaming via macros. I couldn't find a way to make a conventional diff patch that renames files with changes like git does. But I _was_ able to make concise git commits on top of upstream i2cdevlib that do the file renaming and changes all in one go. I was also able to cherry-pick our Encoder changes on top of upstream.

Here's my proposition for Encoder and I2Cdev. (MPU9150 is actually inside of the I2Cdev project upstream)
 - <http://github.com/pitt-ras/Encoder>
 - <http://github.com/pitt-ras/i2cdevlib> (take a look at the diffs for this, it's pretty great)

Each has an 'upstream' branch that tracks the upstream master branch, and our changes are on 'pitt-micromouse'. This puts us in a good position for dealing with future upstream changes.

Associated changes in this repo are in #85.

This was all super tedious and annoying and awful, but now I think it looks pretty good. Somebody better give me a trophy. :-)

What do you think?

**Comment by amiller27** [comment]
![image](https://cloud.githubusercontent.com/assets/4535296/21969565/3ed6a870-db6d-11e6-90ac-341c6ccb1b11.png)

This is the most nice-looking terrible hack I've ever seen
