### ISSUE TITLE
Add IMU functionality

### ISSUE THREAD

**Issue by QuentinTorg** [xaviertorgerson/micromouse#8]
We have an MPU-9150 accelerometer/gyroscope/magnetometer that can be used for error checking our motion.  This is a great resource to read before getting started with this.  https://github.com/kriswiner/MPU-6050/wiki/Affordable-9-DoF-Sensor-Fusion
The full motion processing library is probably overkill for us, but the ideas are useful.  kriswiner also has a library prewritten for the MPU-9150 that we can probably use.  

Ideally, the functions in sensors_orientation.cpp will just output the measured distance or rotation seen by the MPU so that it can be used for error checking during fast motions.  Depending on the accuracy, hopefully we will eventually be able to use these functions to determine if our wheels slipped during our motion, and then be able to compensate for the slip.  

Getting accurate data from these functions will probably require using the MPU-9150's FIFO buffer, and an interrupt that tells the teensy when the buffer is full.

**Comment by QuentinTorg** [comment]
The magnetometer may be too greatly affected by our motors and encoders to give us usable data

**Comment by QuentinTorg** [comment]
During a straight forward motion, the drift of the gyro could be removed by taking into account what the centripetal acceleration should have been during that motion.  If the gyro says that there was a rotation, but the accelerometer saw no centripetal acceleration during that time, then the rotation that the gyro saw should be removed or at least made smaller than was measured.

**Comment by amiller27** [comment]
Gyro drift probably isn't going to be a problem, and if it is, drift in the gyro is going to be comparable to the noise level in the accelerometer.  The gyro is currently drifting by about a hundredth of a degree every few seconds while stationary, which would require accelerometer noise less than on the order of a micro g.  We could put a low pass filter on the accelerometer to get the noise level down a little, but I think the gyro alone should be enough.

**Comment by xaviertorgerson** [comment]
Probably won't get it better than a hundredth of a degree drift unless you get the earth to stop spinning.

**Comment by QuentinTorg** [comment]
Can we create a gyro_rotate(angle) function that uses only the gyro to make pivot turns of the inputted angle to test on Saturday?

we can decide on a reasonable rotational velocity for a turn and that will be a set parameter that doesn't change.  Then it will work similarly to motion_forward in that it accelerates up to the rotational velocity, moves, then decelerates to 0, stopping at the final angle.

It should try to match the implementation that will be used in motion_forward as closely as possible as far as forwarding gyro error into a PID function, that generates an encoder offset.  

It may also be potentially useful to have a gyro_hold(time) function that holds the current rotational position for the input time.  The error should be handled identically to the above function, it should just never change the set point angle.
